### ISSUE TITLE
Toasted not firing notification, `label` is undefined. 

### ISSUE THREAD

**Issue by noahlocke** [kirschbaum-development/nova-inline-select#11]
Here's my Resource code:

```php
$this->when(
  isAdmin($request->user()),
    InlineSelect::make('Status', 'status_id')
      ->options(Status::get()->pluck('name','id')->all())  
      ->inlineOnIndex()
      ->inlineOnDetail()
      ->disableTwoStepOnIndex() 
      ->disableTwoStepOnDetail()
),
```

When I change the value of the `InlineSelect` field, the value updates successfully, but I get nothing from Toatsted (should see something like *"Status updated to `${option.label}`"*)

Here's what I'm getting from the Console:

![Screen Shot 2019-09-02 at 9 10 01 PM](https://user-images.githubusercontent.com/6596677/64139582-0524e200-cdc7-11e9-99df-10d315ddcd9b.png)

Here's what I've got in Vue DevTools, looks like I've got a label/value:

![Screen Shot 2019-09-02 at 9 09 43 PM](https://user-images.githubusercontent.com/6596677/64139543-df97d880-cdc6-11e9-8694-8916472879be.png)

**Comment by brandonferens** [comment]
@noahlocke Thanks for the good documentation on the issue. I'll review your PR soon.

**Comment by brandonferens** [comment]
I made some simple updates to your PR to allow for looser comparisons. Thanks!

**Comment by skoyah** [comment]
hey @brandonferens  I'm having this issue also with the latest release. Did something break?

The problem seems to appear if the database column is nullable by default.
