### ISSUE TITLE
[Feature request] inlineOnLenses()

### ISSUE THREAD

**Issue by skoyah** [kirschbaum-development/nova-inline-select#14]
Would be great if we could make the same functionality on lenses as well.

I'm working on a project where the user must be able to update a field inline on a lenses page. 

Currently it is only possible to use this package on Index and Detail pages.

`inlineOnLenses()` could even accept a single lens or an array of the resource related lenses:

```php
inlineOnLenses(LensesOne::class)

// Or..

inlineOnLenses([LensesOne::class, LensesTwo::class])
```

What do you think @kirschbaum ? Is this a nice feature to implement? Is it hard to work on it?

**Comment by brandonferens** [comment]
This is a great feature idea @skoyah. I will look into this.

**Comment by brandonferens** [comment]
This has been added to the package in #17 and pushed in release https://github.com/kirschbaum-development/nova-inline-select/commit/25ac3533ea73392b5befaccbfeb0c484b32d2761. Thanks again for the suggestion @skoyah!
