### ISSUE TITLE
$toasted not showing when changing value

### ISSUE THREAD

**Issue by skoyah** [kirschbaum-development/nova-inline-select#19]
After some debugging, I think the problem lies in the following code:

https://github.com/kirschbaum-development/nova-inline-select/blob/25ac3533ea73392b5befaccbfeb0c484b32d2761/resources/js/components/mixins/inline.js#L25

This piece of code is trying to set the label based on the `field.value`. The problem is that this is the old `value` and not the new one. 

Fixing this would tackle 2 issues:

- First, if the old value is null, $toasted will never show up because is trying to get `label` on null.
- Second, if there was an old value, then the $toasted will show but referencing the old value and not the updated one.

This issues is related with #11 

Can anyone confirm if the issue still persists?

**Comment by vlinde** [comment]
Some news about this issue?

**Comment by skoyah** [comment]
I have mad a PR #20  that fixes this issue, but still waiting for the mantainer's feedback. :(
