### ISSUE TITLE
When flag a field as required, the inline edit in index does not work

### ISSUE THREAD

**Issue by lisotton** [kirschbaum-development/nova-inline-select#42]
### Problem
As the inline edit uses the default Nova endpoint to save data, it applies the validation rules for other fields.

### Suggestion
My suggestion is to create a new endpoint only to save the data from the inline editing, which does not apply the the validation rules.

**Comment by czemu** [comment]
I confirm, this is a serious issue that makes the package unusable.

**Comment by bakicdj** [comment]
what is the status of this?

**Comment by brandonferens** [comment]
The above PR has been merged. However, version 2.0 of this package has been released for Nova 4, so if you are able to upgrade, please do so.
