### ISSUE TITLE
Error: Request fail with status code 422

### ISSUE THREAD

**Issue by ronnytorresmtz** [kirschbaum-development/nova-inline-select#5]
Hi,

When I select the option the system throw this error 

Error: Request fail with status code 422

My code is:

InlineSelect::make('Status')->options([
                'Pendiente' => 'Pendiente',
                'En Proceso' => 'En Proceso',
                'En Deploy' => 'En Deploy',
                'Terminada' => 'Terminada',
            ])
            ->inlineOnIndex()
            ->disableTwoStepOnIndex(),

Do I miss something?

Thks,

**Comment by brandonferens** [comment]
@ronnytorresmtz based on your description of the error, it is a validation rules error. Take a peak at the [validation caveats](https://github.com/kirschbaum-development/nova-inline-select#validation-caveats) section of the inline select docs.

**Comment by greit-solution** [comment]
I have the same problem.

**Comment by ziming** [comment]
Same problem too. I even defined the sometimes update rules as said.

**Comment by ziming** [comment]
Ah okay Looking at the XHR response. It run validation against all your other Nova form fields too.

So possible your seeder didn't seed a column value, but in your nova validation you mark it required and this throw an error, even though that field is not status field

Not an expected behaviour. Hope this could be fixed in this package

**Comment by brandonferens** [comment]
@ziming Can you post the XHR response so I can take a look at it? Or at least the failure response? It would also be helpful to see the Nova field code with this inline select field be used.

Thanks!

**Comment by 4n70w4** [comment]
Laravel Nova 2.9.3

```php
            MorphTo::make(__('Payer'), 'payer')->types([
                    Organization::class,
                    NaturalPerson::class
                ]
            )->searchable()->updateRules('sometimes'),
```

But exception:

Status Code: 422 

```json
{"message":"The given data was invalid.","errors":{"payer_type":["\u041f\u043e\u043b\u0435 payer type \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f."]}}
```

**Comment by 4n70w4** [comment]
Workaround for `MorphTo`:

use `->nullable(true)` instead `->updateRules('sometimes')`.

**Comment by 4n70w4** [comment]
https://github.com/laravel/nova-issues/issues/2331

**Comment by aiman1717a** [comment]
> Ah okay Looking at the XHR response. It run validation against all your other Nova form fields too.
> 
> So possible your seeder didn't seed a column value, but in your nova validation you mark it required and this throw an error, even though that field is not status field
> 
> Not an expected behaviour. Hope this could be fixed in this package

Having the same issue, were you able to fix it somehow?
