### ISSUE TITLE
Default/"Choose an Option" option should hide Update button

### ISSUE THREAD

**Issue by adammparker** [kirschbaum-development/nova-inline-select#6]
After you choose an option in the drop-down, if you switch back to the "Choose an option" option, the "Update" button is still displayed/enabled:

![image](https://user-images.githubusercontent.com/5186174/62490302-fed72200-b796-11e9-9b8b-034e2ad661f1.png)

Causes a 500:
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'status' cannot be null ...`

**Comment by brandonferens** [comment]
Fixed on 300c344
