### ISSUE TITLE
Hydrate field with current value

### ISSUE THREAD

**Issue by noahlocke** [kirschbaum-development/nova-inline-select#7]
Sorry if I'm just missing this, but is it possible for the select field to be hydrated with the model/resources's current value? When I load up the index view, the select field is blank, but I'd expect it to show the current value.

**Comment by noahlocke** [comment]
Never mind, my options syntax was off.

**Comment by brandonferens** [comment]
No worries @noahlocke. We just released version `1.0.3` which addressed this issue, so glad it's working for you.
